#!/usr/bin/env bash
# SPDX-License-Identifier: AGPL-3.0-only
# Post-commit hook: cache commit metadata for nerdtime devlog.
# Install: git config core.hooksPath .githooks
nerd devlog cache-commit 2>/dev/null || true
